### ISSUE TITLE
ProteomeXchange notification after publication of PXD012889 via PX file did not work

### ISSUE THREAD

**Issue by germa** [PRIDE-Archive/pride-curation-scripts#14]
PXD012889 is public in PRIDE, but the sending of the PX message to ProteomeXchange failed:
Validating PX message file:
XML schema validation on PXD012889.xml
FATAL XML Parsing error detected on line 10
see more ./log/publication/PXD012889-publication.log

runUpdatePXXml.sh also exited:
javax.xml.bind.UnmarshalException: null
see more ./log/publication/PXD012889-update-px-xml.log

**Comment by sureshhewabi** [comment]
@germa Error says:

```
Validating PX message file:
XML schema validation on PXD012889.xml
FATAL XML Parsing error detected on line 10
  Fatal Error message: An invalid XML character (Unicode: 0x1) was found in the element content of the document.
```
If you have a look in the XML line 10:
`<Description> ...... absolute fold change^A1.5 ...... </Description>`

So this ^ character matters.

**Comment by germa** [comment]
Issue solved (removed the invalid character)
