### ISSUE TITLE
 Xml Schema Validation error

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#17]
Removed the special character from the element "<run id" but still gives the error. 

Error - 
================= Xml schema validation ===============

FILE: 27Dec2017_Suping_ShoExp1.mzML
VALIDATION MESSAGE: (1) Non-fatal XML Parsing error detected on line 1, (2) Error message: cvc-attribute.3: The value '27Dec2017SupingShoExp118Feb2019' of attribute 'id' on element 'run' is not valid with respect to its type, 'ID'., (3) Error message: cvc-datatype-valid.1.2.1: '27Dec2017SupingShoExp118Feb2019' is not a valid value for 'NCName'.

Ticket number -
1-20190306-35424-RESUB1

**Comment by sureshhewabi** [comment]
An xsd:ID value must be an NCName. This means that it must **start with a letter or underscore**, and can only contain letters, digits, underscores, hyphens, and periods.

### Substitute string in Mac:
sed -i .bak 's/27Dec2017SupingShoExp118Feb2019/Dec2017SupingShoExp118Feb2019/g' 27Dec2017_Suping_ShoExp1_edited.mzML

### Validate XML file against Schema(XSD) file:
xmllint --noout --schema mzML1.1.0.xsd 27Dec2017_Suping_ShoExp1_edited.mzML

**Comment by sureshhewabi** [comment]
@deeptijk Did we manage to solve this issue or do you need any help on this?
