### ISSUE TITLE
XML Schema Validation

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#18]
Got this error while locally validating mzid -

1. element Modification: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}Modification’: This element is not expected. Expected is one of ( {http://psidev.info/psi/pi/mzIdentML/1.1}SubstitutionModification, {http://psidev.info/psi/pi/mzIdentML/1.1}cvParam, {http://psidev.info/psi/pi/mzIdentML/1.1}userParam ).
/Users/jaiswal/Desktop/PigTooth.mzid:40751: element Modification: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}Modification’: This element is not expected. Expected is one of ( {http://psidev.info/psi/pi/mzIdentML/1.1}SubstitutionModification, {http://psidev.info/psi/pi/mzIdentML/1.1}cvParam, {http://psidev.info/psi/pi/mzIdentML/1.1}userParam ).
/Users/jaiswal/Desktop/PigTooth.mzid:54148: element Modification: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}Modification’: This element is not expected. Expected is one of ( {http://psidev.info/psi/pi/mzIdentML/1.1}SubstitutionModification, {http://psidev.info/psi/pi/mzIdentML/1.1}cvParam, {http://psidev.info/psi/pi/mzIdentML/1.1}userParam ).
/Users/jaiswal/Desktop/PigTooth.mzid:54555: element Modification: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}Modification’: This element is not expected. Expected is one of ( {http://psidev.info/psi/pi/mzIdentML/1.1}SubstitutionModification, {http://psidev.info/psi/pi/mzIdentML/1.1}cvParam, {http://psidev.info/psi/pi/mzIdentML/1.1}userParam ).
/Users/jaiswal/Desktop/PigTooth.mzid:60320: element Modification: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}Modification’: This element is not expected. Expected is one of ( {http://psidev.info/psi/pi/mzIdentML/1.1}SubstitutionModification, {http://psidev.info/psi/pi/mzIdentML/1.1}cvParam, {http://psidev.info/psi/pi/mzIdentML/1.1}userParam ).
/Users/jaiswal/Desktop/PigTooth.mzid:61746: element Modification: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}Modification’: This element is not expected. Expected is one of ( {http://psidev.info/psi/pi/mzIdentML/1.1}SubstitutionModification, {http://psidev.info/psi/pi/mzIdentML/1.1}cvParam, {http://psidev.info/psi/pi/mzIdentML/1.1}userParam ).

2. element SpectrumIdentificationItem: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}SpectrumIdentificationItem’: Duplicate key-sequence [‘SII_275319_784246’] in unique identity-constraint ‘{http://psidev.info/psi/pi/mzIdentML/1.1}PK_DATAADSILSIRSII’.
/Users/jaiswal/Desktop/PigTooth.mzid:126575: element SpectrumIdentificationItem: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}SpectrumIdentificationItem’: Duplicate key-sequence [‘SII_275319_784246’] in unique identity-constraint ‘{http://psidev.info/psi/pi/mzIdentML/1.1}PK_DATAADSILSIR’.
/Users/jaiswal/Desktop/PigTooth.mzid:126580: element SpectrumIdentificationItem: Schemas validity error : Element ‘{http://psidev.info/psi/pi/mzIdentML/1.1}SpectrumIdentificationItem’: Duplicate key-sequence [‘SII_275319_784246’] in unique identity-constraint ‘{http://psidev.info/psi/pi/mzIdentML/1.1}PK_DATAADSILSIRSII’.

Validation failed

**Comment by sureshhewabi** [comment]
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=331618

**Comment by sureshhewabi** [comment]
There are three issues I found in their file:

![Screen Shot 2019-03-25 at 10 49 57](https://user-images.githubusercontent.com/5387193/54913965-d8050700-4eeb-11e9-933c-326402de1c8a.png)

1. `<Modification>` tag should appear before `<SubstitutionModification>` tag 
2. I can see `^M` characters at the end of each element
3. `SpectrumIdentificationItem` ids cannot be duplicated, but they have duplicated values

**Comment by sureshhewabi** [comment]
![Screen Shot 2019-03-25 at 11 08 54](https://user-images.githubusercontent.com/5387193/54915171-74c8a400-4eee-11e9-88a0-69e3ce4578f9.png)
