### ISSUE TITLE
A fatal error has been detected by 

### ISSUE THREAD

**Issue by germa** [PRIDE-Archive/pride-curation-scripts#20]
more ./log/validation/1-20190226-143712-RESUB2-validation.log

**Comment by sureshhewabi** [comment]
FATAL XML Parsing error detected on line 9462790
  Fatal Error message: XML document structures must start and end within the same entity.
FATAL XML Parsing error detected on line 9462790
  Fatal Error message: XML document structures must start and end within the same entity.

**Comment by sureshhewabi** [comment]
![Screen Shot 2019-03-25 at 13 47 36](https://user-images.githubusercontent.com/5387193/54924586-a187b600-4f04-11e9-83ae-fd88b9570605.png)

/nfs/pride/prod/archive/1-20190226-143712-RESUB2/submitted$ tail meta_rep3.mzid

meta_rep3.mzid file is a half complete one!

**Comment by sureshhewabi** [comment]
@germa Can we close this issue?

**Comment by germa** [comment]
no, not yet. Validation of 1-20190226-143712-RESUB-0006 is still running

**Comment by germa** [comment]
done (PXD013452).
