### ISSUE TITLE
Broken link in proteomeXchange

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-curation-scripts#27]
**Based in the Juan's Email:**

In PRIDE the link (correct) is ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/03/PXD009602 
In Proteome Central, the link is ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2018/05/PXD009602

So, I guess there was some kind of resubmission when the data was public. This is probably not taken into account in the pipeline now.

**Comment by ypriverol** [comment]
@sureshhewabi which email?

**Comment by sureshhewabi** [comment]
Hi Yasset/Suresh,

See the e-mail received yesterday.

In PRIDE the link (correct) is ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/03/PXD009602 
In Proteome Central, the link is ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2018/05/PXD009602

So, I guess there was some kind of resubmission when the data was public. This is probably not taken into account in the pipeline now.

As I mentioned, before maybe we have to plan a big re-sync of PRIDE datasets in PC since there are other well-known problems:

http://proteomecentral.proteomexchange.org/cache/findMissingArticles.html

In this particular case, the three datasets that appear to be private in ProteomeCentral (PXD004092, PXD003887 and PXD001768) are actually public in PRIDE.

And there must be other analogous issues as well I guess…

Thanks,

Juan

**Comment by sureshhewabi** [comment]
Corrected
