### ISSUE TITLE
Project web page is not synchronised - if you click on the page it gives the correct title but not in the first search page.

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#37]
<img width="605" alt="Screenshot 2019-11-21 at 13 37 08" src="https://user-images.githubusercontent.com/38948179/69343367-6f7e4d80-0c65-11ea-8adf-b235b4f067ee.png">
<img width="541" alt="Screenshot 2019-11-21 at 13 37 18" src="https://user-images.githubusercontent.com/38948179/69343384-74430180-0c65-11ea-89d7-bdc7ace3ff76.png">

**Comment by sureshhewabi** [comment]
@deeptijk Done!

https://www.ebi.ac.uk/pride/archive/simpleSearch?q=PXD016146&submit=Search
https://www.ebi.ac.uk/pride/archive/projects/PXD016146
